# Generated by Django 3.1.2 on 2020-11-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='active',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
