# Generated by Django 3.1.2 on 2020-11-11 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('news', '0002_newsarticle_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='active',
            field=models.IntegerField(blank=True, default=1, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='main_image_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.storagefile', verbose_name='Заглавная картинка'),
        ),
    ]
