# Generated by Django 3.1.2 on 2020-11-11 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5hash', models.CharField(max_length=32)),
                ('ext', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('content_type', models.CharField(max_length=255)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StorageAudio',
            fields=[
                ('storagefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.storagefile')),
                ('duration', models.IntegerField()),
            ],
            bases=('utils.storagefile',),
        ),
        migrations.CreateModel(
            name='StorageImage',
            fields=[
                ('storagefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.storagefile')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
            bases=('utils.storagefile',),
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['md5hash'], name='utils_stora_md5hash_40b266_idx'),
        ),
    ]
