# Generated by Django 3.1.2 on 2020-11-03 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_modify', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('fio_candidate', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('rayon', models.CharField(max_length=255)),
                ('settlement', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StreetTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StreetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_modify', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door2door.campaignmodel')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door2door.streettypemodel')),
            ],
        ),
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_modify', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=10)),
                ('type', models.IntegerField()),
                ('is_openned', models.IntegerField()),
                ('is_interesed', models.IntegerField()),
                ('is_recieved', models.IntegerField()),
                ('problem_description', models.TextField(default='')),
                ('comment', models.CharField(default='', max_length=255)),
                ('is_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door2door.housemodel')),
                ('street_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door2door.streetmodel')),
            ],
        ),
    ]
