# Generated by Django 3.1.2 on 2020-11-04 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('door2door', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streettypemodel',
            options={'verbose_name': 'Тип улицы', 'verbose_name_plural': 'Типы улиц'},
        ),
        migrations.RenameField(
            model_name='housemodel',
            old_name='is_group_id',
            new_name='group_id',
        ),
        migrations.AlterField(
            model_name='campaignmodel',
            name='fio_candidate',
            field=models.CharField(max_length=255, verbose_name='ФИО кандидата'),
        ),
        migrations.AlterField(
            model_name='campaignmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название кампании/обхода'),
        ),
        migrations.AlterField(
            model_name='campaignmodel',
            name='rayon',
            field=models.CharField(max_length=255, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='campaignmodel',
            name='region',
            field=models.CharField(max_length=255, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='campaignmodel',
            name='settlement',
            field=models.CharField(max_length=255, verbose_name='Населённый пункт'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='comment',
            field=models.CharField(default='', max_length=255, verbose_name='Произвольный комментарий'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='is_interesed',
            field=models.IntegerField(verbose_name='Интерес'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='is_openned',
            field=models.IntegerField(verbose_name='Отрыли'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='is_recieved',
            field=models.IntegerField(verbose_name='Приняли'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='problem_description',
            field=models.TextField(default='', verbose_name='Проблемы/наказы избирателя'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='type',
            field=models.IntegerField(verbose_name='Тип дома'),
        ),
        migrations.AlterField(
            model_name='streetmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название улицы'),
        ),
        migrations.AlterField(
            model_name='streetmodel',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door2door.streettypemodel', verbose_name='Тип улицы'),
        ),
    ]
