# Generated by Django 3.1.2 on 2020-11-04 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('door2door', '0002_auto_20201104_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='door2door.housemodel'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='is_interesed',
            field=models.IntegerField(null=True, verbose_name='Интерес'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='is_openned',
            field=models.IntegerField(null=True, verbose_name='Отрыли'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='is_recieved',
            field=models.IntegerField(null=True, verbose_name='Приняли'),
        ),
    ]
