# Generated by Django 3.1.2 on 2020-11-10 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('door2door', '0003_auto_20201104_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Произвольный комментарий'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='door2door.housemodel'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='problem_description',
            field=models.TextField(blank=True, default='', verbose_name='Проблемы/наказы избирателя'),
        ),
    ]
